// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqsBpNelOzawkcn-t2z1VFcsOl1Cb1TNw',
    appId: '1:9386669216:web:f185759db59bf4bdac45c5',
    messagingSenderId: '9386669216',
    projectId: 'elib-vce',
    authDomain: 'elib-vce.firebaseapp.com',
    storageBucket: 'elib-vce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnzIK5p6WlsSLarXB_AOTSxhUH_xysWz0',
    appId: '1:9386669216:android:93430d964ffb3fd3ac45c5',
    messagingSenderId: '9386669216',
    projectId: 'elib-vce',
    storageBucket: 'elib-vce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM6DPUayyRtme9MeBxMluwDCYS0i0WU78',
    appId: '1:9386669216:ios:77b5c9ed2e8497acac45c5',
    messagingSenderId: '9386669216',
    projectId: 'elib-vce',
    storageBucket: 'elib-vce.appspot.com',
    iosClientId: '9386669216-8bstnkibreo6ik00ec88brnrecp5d8g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eVce',
  );
}
